version: '{build}'

pull_requests:
  do_not_increment_build_number: true

branches:  
  only:
  - master

os: Visual Studio 2017

configuration: Release

build_script:
- ps: .\Build.ps1 -Target Pack

test: off  

nuget:
  disable_publish_on_pr: true

artifacts:
- path: artifacts\**\*.nupkg
  name: NuGet

deploy:
- provider: NuGet
  name: ci
  server: https://www.myget.org/F/datetimeextensions/api/v2/package
  api_key:
    secure: YcG+jkipdRz1ahroGCiCndKtgEcRaVtEzQYSNp5Mx5ULWPpZZ/MvwMsggLCYZ3bH
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  name: production
  api_key:
    secure: c18PmLObjM4XzNKNj8/LzYty11gya98+IerJXipzMmL9wgmHS6cGAJWYpJkDxmU2
  on:
    branch: master
    appveyor_repo_tag: true