apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: customresources.csharp.com
spec:
  group: csharp.com
  version: v1alpha1
  names:
    kind: CResource
    plural: customresources
  scope: Namespaced